# Generated by Django 3.2.6 on 2021-08-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image_main', models.ImageField(upload_to='photos/')),
                ('image_sec', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
